# workflow name
name: Generate release-artifacts

# on events
on:
  push:
    tags: 
        - "*.*"

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: echo "PROJECT_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.0.2
        env:
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
        with:
            platforms: 'linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64'
            package: ''
            name: ${PROJECT_NAME}
            compress: 'false'
            dest: 'dist'
      - name: Release artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/tg2slck-linux-amd64,dist/tg2slck-linux-arm64,dist/tg2slck-darwin-amd64,dist/tg2slck-darwin-arm64,dist/tg2slck-windows-amd64.exe"
          # bodyFile: "body.md"
          tag: ""
          allowUpdates: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
