# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types: 
        - created

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: ''
            name: 'tg2slck'
            compress: 'true'
            dest: 'dist'
      - name: Release artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/tg2slck-linux-amd64.tar.gz,dist/tg2slck-darwin-amd64.tar.gz,dist/tg2slck-windows-amd64.tar.gz"
          # bodyFile: "body.md"
          tag: ""
          allowUpdates: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
