# workflow name
name: Generate release-artifacts

# on events
on:
  push:
    tags: 
        - "*.*"

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.0.2
        with:
            platforms: 'linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64'
            package: ''
            name: ${{ github.event.repository.name }}
            compress: 'false'
            dest: 'dist'
      - name: Release artifacts
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: > 
            dist/${{ github.event.repository.name }}-linux-amd64,
            dist/${{ github.event.repository.name }}-linux-arm64,
            dist/${{ github.event.repository.name }}-darwin-amd64,
            dist/${{ github.event.repository.name }}-darwin-arm64,
            dist/${{ github.event.repository.name }}-windows-amd64.exe
          allowUpdates: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
